version: "3.7"

services:
  client:
    build: ./client
    working_dir: /client
    container_name: client
    command: node scripts/run.js
    volumes:
      - ./client/.svelte-kit/:/client/.svelte-kit/
      - ./client/patches/:/client/patches/
      - ./client/scripts/:/client/scripts/
      - ./client/src/:/client/src/
      - ./client/static/:/client/static/
      - ./client/package.json:/client/package.json
      - ./client/pnpm-lock.yaml:/client/pnpm-lock.yaml
      - ./client/postcss.config.js:/client/postcss.config.js
      - ./client/svelte.config.js:/client/svelte.config.js
      - ./client/tailwind.config.ts:/client/tailwind.config.ts
      - ./client/vite.config.ts:/client/vite.config.ts
    env_file:
      - .env
    environment:
      - PUBLIC_IS_DOCKER=true
      - PUBLIC_ENV=dev

  server:
    build: ./server
    working_dir: /server
    container_name: server
    command: bash run.sh
    volumes:
      - ./server/:/server
    env_file:
      - .env

  proxy:
    image: nginx
    ports:
      - 4444:80
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - client
      - server
